---
apiVersion: v1
kind: Service
metadata:
  name: newbie-bot-dev
  namespace: cw
  labels:
    app: newbie-dev
    role: frontend
spec:
  ports:
  - port: 443
    targetPort: 5000
  selector: {
    app: newbie-dev,
    role: frontend,
  }
---
apiVersion: v1
kind: Service
metadata:
  name: newbie-db-dev
  namespace: cw
  labels:
    app: newbie-dev
    role: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector: {
    app: newbie-dev,
    role: backend,
  }
