---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: newbie-db-stage
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-01edcdddc946a6d14
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: newbie-db-stage
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
